feat: concentrated liquidity UI - final
pangolindex/components pull request #332
Opened 2023-03-21 14:34 UTC by bilalcorbacioglu

Summary
This PR includes the Price Graph component.

Links
[Figma](https://www.figma.com/file/gxxYcgJbGcL2pGs3LVrLfB/Pangolin-Project?node-id=4864%3A87032&t=IheBvWmAGqze8puP-0)
[Clickup Doc](https://app.clickup.com/36619926/docs/12xhmp-8820/12xhmp-10520)

2023-03-22 19:14 UTC, SarjuHansaliya requested changes
@bilalcorbacioglu I have added some comments, overall its looking good. can you also make sure modal looks proper when screen height is small. its not scrollable for smaller height.

2023-03-22 23:56 UTC, bilalcorbacioglu commented on src/components/Column/index.tsx
> +export const AutoColumn = styled.div<{
I've done it.

2023-03-23 13:22 UTC, SarjuHansaliya requested changes

2023-03-23 13:29 UTC, SarjuHansaliya commented on src/components/SwapWidget/TokenWarningModal/index.tsx
> +import { AutoColumn } from 'src/components/Column';
awesome thanks

2023-03-24 14:12 UTC, SarjuHansaliya approved these changes

2023-03-24 14:13 UTC, merged