feat: earnwidget conc liq
pangolindex/components pull request #364
Opened 2023-04-18 02:16 UTC by bilalcorbacioglu

## Summary
Conc Liq

=> Earn - Collect Fees Function
=> Remove Liquidity

2023-04-18 14:00 UTC, SarjuHansaliya requested changes

2023-04-19 15:44 UTC, bilalcorbacioglu commented on src/components/ConcentratedLiquidity/DetailModal/EarnWidget/Remove/index.tsx
> +                  <TextInput
1. Handled
2 -> Abdullah said that we don't need it.
3 -> Abdullah said we need to show for UX.
4. Let me handle it in bug PR.

2023-04-19 18:18 UTC, SarjuHansaliya commented on src/components/ConcentratedLiquidity/DetailModal/EarnWidget/index.tsx
> +    if (!chainId || !library || !account || !provider) return;
sure make sense @bilalcorbacioglu

2023-04-19 18:22 UTC, SarjuHansaliya approved these changes

2023-04-19 18:22 UTC, merged