Update SelectTokenDrawer and add Portfolio widget
pangolindex/components pull request #41
Opened 2022-06-01 00:02 UTC by prodesert22

- Removed Avax from search list on SelectTokenDrawer
![image](https://user-images.githubusercontent.com/37405304/171302719-b854a45b-a704-4f85-abb5-549253ab0f5a.png)
- [Added portfolio widget](https://github.com/pangolindex/components/commit/244a2b16b330790d23874bc4c8173e3ee48800bf)
![image](https://user-images.githubusercontent.com/37405304/171302753-3cf32426-c416-4587-abdc-a40df94715db.png)

2022-06-01 10:06 UTC, SarjuHansaliya requested changes

2022-06-01 10:06 UTC, SarjuHansaliya commented on src/components/SwapWidget/SelectTokenDrawer/index.tsx
> +    return filterTokens(tokens, searchQuery);
AVAX is removed from top position even if we don't search anything. 

![Screenshot 2022-06-01 at 3 32 00 PM](https://user-images.githubusercontent.com/6604146/171380298-144bd61e-e424-43de-8a5b-d40d996477ec.png)

it should work how it is working in prod.


https://user-images.githubusercontent.com/6604146/171380252-53699c85-8652-4010-999d-cd7f3f4b7eaf.mov

2022-06-01 12:55 UTC, prodesert22 commented on src/components/Portfolio/Portifolio.tsx
> +            {chain.name}
Not necessary because always string
https://github.com/pangolindex/sdk/blob/67f347a948e13c1136c4ca8cfc8997bb4abcc4af/src/chains.ts#L16

2022-06-02 06:06 UTC, SarjuHansaliya requested changes

2022-06-06 04:04 UTC, SarjuHansaliya approved these changes

2022-06-06 04:05 UTC, merged