Widget Changes
pangolindex/components pull request #78
Opened 2022-07-26 21:13 UTC by bmino

Missing the following version bumps:

exchange-contracts
sdk

2022-08-01 22:29 UTC, bmino commented
The appropriate version bumps have been published and included

2022-08-05 07:27 UTC, SarjuHansaliya requested changes

2022-08-05 07:27 UTC, SarjuHansaliya commented on src/utils/index.ts
>    }
after this change, few files are giving typescript error. run `./node_modules/.bin/tsc`

![Screenshot 2022-08-05 at 12 56 21 PM](https://user-images.githubusercontent.com/6604146/183024935-f2257ddc-af6f-47d8-8c47-50edd0a24b85.png)

2022-08-08 04:10 UTC, SarjuHansaliya approved these changes

2022-08-08 04:10 UTC, merged